#!/usr/bin/env node
/**
 * Vendor BitRouter Cloud's `GET /v1/models` response schema.
 *
 *   node scripts/refresh-schema.mjs           # write schema/models.schema.json
 *   node scripts/refresh-schema.mjs --check   # exit 1 if the vendored copy is stale
 *
 * BitRouter Cloud generates an OpenAPI document from the Rust types that
 * serialize the response (`ModelListResponse` / `ModelResponse`, via `aide`),
 * serves it unauthenticated at `/openapi.json`, and syncs it into the public
 * bitrouter-docs repository on every release. So the wire contract this plugin
 * maps against is *published*, and there is no need to guess at it, diff live
 * responses, or hold an API key in CI to find out when it moves.
 *
 * The copy is vendored rather than fetched at test time on purpose: the suite
 * that gates merges has to be deterministic and offline. Refreshing is the
 * moving part, and it happens in a scheduled workflow that opens a pull
 * request — where a change to the contract shows up as a reviewable diff
 * against the assertions in `test/schema.test.ts`.
 *
 * Nothing time-varying is written into the output, or `--check` would fail on
 * every run regardless of whether the contract had moved.
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "schema", "models.schema.json");

/** Where the contract is published. Named in the vendored file regardless of
 * where this run actually read it from, so the provenance recorded in the
 * repository is the canonical source and not somebody's local override. */
const CANONICAL_URL = "https://api.bitrouter.ai/openapi.json";
const SPEC_URL = process.env.BITROUTER_OPENAPI_URL ?? CANONICAL_URL;
const check = process.argv.includes("--check");

/** Recursively key-sort, so a cosmetic reordering upstream is not a diff here. */
function sorted(value) {
  if (Array.isArray(value)) return value.map(sorted);
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.keys(value)
        .sort()
        .map((k) => [k, sorted(value[k])]),
    );
  }
  return value;
}

function extract(spec) {
  const schema = spec?.paths?.["/v1/models"]?.get?.responses?.["200"]?.content?.[
    "application/json"
  ]?.schema;
  if (!schema || typeof schema !== "object") {
    throw new Error(
      `no 200 application/json schema for GET /v1/models in ${SPEC_URL} — the spec moved, and this script needs updating before the vendored copy can be trusted`,
    );
  }
  return schema;
}

/**
 * The spec source. `BITROUTER_OPENAPI_URL` may also name a local file, which
 * is how this runs behind a network that will not let the process out — fetch
 * the document by whatever means work, then point this at it.
 */
async function loadSpec() {
  if (!/^https?:/i.test(SPEC_URL)) {
    return JSON.parse(readFileSync(SPEC_URL.replace(/^file:\/\//, ""), "utf8"));
  }
  const res = await fetch(SPEC_URL, { headers: { accept: "application/json" } });
  if (!res.ok) throw new Error(`GET ${SPEC_URL} — HTTP ${res.status}`);
  return res.json();
}

const rendered =
  JSON.stringify(
    {
      $comment:
        `The 200 response schema for GET /v1/models, extracted verbatim from BitRouter Cloud's published OpenAPI document at ${CANONICAL_URL}. Generated by scripts/refresh-schema.mjs — do not hand-edit; run \`npm run schema:refresh\`.`,
      ...sorted(extract(await loadSpec())),
    },
    null,
    2,
  ) + "\n";

let current = null;
try {
  current = readFileSync(OUT, "utf8");
} catch {
  /* first run */
}

if (current === rendered) {
  console.log("schema/models.schema.json is up to date");
  process.exit(0);
}

if (check) {
  console.error(
    "schema/models.schema.json is stale — BitRouter Cloud's published contract has moved.\n" +
      "Run: npm run schema:refresh",
  );
  process.exit(1);
}

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, rendered);
console.log(`wrote schema/models.schema.json (from ${SPEC_URL})`);
